import { Router } from "express";
import { Role } from "@prisma/client";
import { auth } from "../../middleware/auth";
import { adminController } from "./admin.controller";
const router = Router();
router.get("/users", auth(Role.ADMIN), adminController.getAllUsers);
router.patch("/users/:id", auth("ADMIN"), adminController.updateUserStatus);
router.get("/gear", auth(Role.ADMIN), adminController.getAllGear);
router.get("/rentals", auth(Role.ADMIN), adminController.getAllRentalOrders);
export const adminRoute = router;
